name: aipod
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-138.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  animations: ^2.0.11
  html: ^0.15.4
  http: ^1.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/podcast_logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/podcast_logo.jpg"  
  web:
    generate: true
    image_path: "assets/podcast_logo.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/podcast_logo.jpg" 
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/podcast_logo.jpg" 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/podcast_logo.jpg
