// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIIEIa6OkeOF-DsiSLT2qCqcUNFkTLlzg',
    appId: '1:586933994579:web:a99ab4ba0f9bcdd493f2a6',
    messagingSenderId: '586933994579',
    projectId: 'pod-ai',
    authDomain: 'pod-ai.firebaseapp.com',
    storageBucket: 'pod-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJ03zRWZ4i_XWDgCj9sUHGGpqtNH-fJ8',
    appId: '1:586933994579:android:86cc93f59f576c1593f2a6',
    messagingSenderId: '586933994579',
    projectId: 'pod-ai',
    storageBucket: 'pod-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJKxWhvDJRZZnhGwFnnyo2VfgHwfs_HP0',
    appId: '1:586933994579:ios:0ece2c7196c334dd93f2a6',
    messagingSenderId: '586933994579',
    projectId: 'pod-ai',
    storageBucket: 'pod-ai.appspot.com',
    iosBundleId: 'com.example.aipod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJKxWhvDJRZZnhGwFnnyo2VfgHwfs_HP0',
    appId: '1:586933994579:ios:0ece2c7196c334dd93f2a6',
    messagingSenderId: '586933994579',
    projectId: 'pod-ai',
    storageBucket: 'pod-ai.appspot.com',
    iosBundleId: 'com.example.aipod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIIEIa6OkeOF-DsiSLT2qCqcUNFkTLlzg',
    appId: '1:586933994579:web:3c506ed82c5b5c4593f2a6',
    messagingSenderId: '586933994579',
    projectId: 'pod-ai',
    authDomain: 'pod-ai.firebaseapp.com',
    storageBucket: 'pod-ai.appspot.com',
  );
}
